### ISSUE TITLE
Example Of External Dependancy Configuraiton

### ISSUE THREAD

**Issue by dannymyers** [welldone-software/gulp-durandal#12]
Please Help!

I can't seem to find an example of how to include references external dependencies for my durandal view models.

For example, I have a lot of code that references jQuery, but I don't want to include jQuery in my built output file. Is this possible? Can someone point me to an example of how to do this?

define(["jquery", "knockout", "custom/koutilities"],
    function ($, ko, koutilitiesl) { ..... });

Thank you!

PS: If this helps, here is what I'm trying to do in "grunt" syntax.

    var requireConfig = {
        baseUrl: '../app/',
        paths: {
            'jquery': '../scripts/jquery-2.1.1',
            'knockout': '../scripts/knockout-3.2.0',
            'toastr': '../scripts/toastr',
            'moment': '../scripts/moment',
            'underscore': '../scripts/underscore',
            'amplify': '../scripts/amplify',
            "text": "../scripts/text",
            "durandal": "../scripts/durandal",
            "plugins": "../scripts/durandal/plugins",
            "transitions": "../scripts/durandal/transitions",
            "dataserviceslib": "../scripts/dataserviceslib",
            "widgets": "../scripts/custom/widgets",
            "scripts": "../scripts",
            "utility": "../scripts/shared/utility",
		"custom": "../scripts/custom",
		"base": "../scripts/custom/base",
        	"constants": "../scripts/custom/constants",
        }
    };

        durandal: {
            main: {
                src: ['../app/**/*.*', '../scripts/durandal/**/*.*', '../scripts/custom/widgets/**/*.*'],
                options: {
                    name: '../scripts/almond-custom',
                    baseUrl: requireConfig.baseUrl,
                    mainPath: '../app/main',
                    paths: mixIn({}, requireConfig.paths, { 'almond': '../scripts/almond-custom.js' }),
                    exclude: ['jquery', 'knockout', 'toastr', 'moment', 'underscore', 'amplify'],
                    optimize: 'none',
                    out: '../app/main-debug.js'
                }
            }
        },

**Comment by danikenan** [comment]
The above code seems to mix the durandal task and rjs (and to be a part of grunt and not gulp)

In any case, for others, you can use `moduleFilter` to exclude modules and the `rjsConfigAdapter` to get full control and ability to change the internally generated rjs config just before it is exectued.
