### ISSUE TITLE
SourceMap-Exclude

### ISSUE THREAD

**Issue by NightkingCH** [welldone-software/gulp-durandal#15]
When I define "generateSourceMaps: false" on the rjsConfigAdapter you still add the sourceMapUrl to the output file which occurs in an 404-Response from the server. This is an unnecessary call.

rjsConfigAdapter: function (rjsConfig) {
            rjsConfig.generateSourceMaps = false;
            return rjsConfig;
 }

Line 114, index.js: 

text += '//# sourceMappingURL=' + path.basename(mapOutput);

Please add a check if the sourcemap is generated! Something like that:

if sourceMapText {
text += '//# sourceMappingURL=' + path.basename(mapOutput);
}

It's silly because you already check if you have to generate the sourceMap-file :).

**Comment by vzaidman** [comment]
got it.
it will be fixed soon.
