### ISSUE TITLE
Build only if newer support

### ISSUE THREAD

**Issue by rockResolve** [welldone-software/gulp-durandal#16]
I want my build task to only run the gulp-durandal plugin if the source files have changed.

The normal gulp solution is to pipe to the build plugin after running gulp-newer
```javascript
    var newer = require('gulp-newer');

    return gulp.src(["inputDir1/**/*.js", "inputDir2/**/*.js", "inputDir3/**/*.html"])
        .pipe(newer(outputPath))
        .pipe(durandal(durandalOptions))
        .pipe(gulp.dest('dummyValue'));         //This is required to create output files
````

However currently gulp-durandal ignores the input stream generated by newer, and so always builds

### Why ###
gulp-durandal does a great job of hiding the complexity of requirejs config from gulp tasks. It is the config that specifies the requirejs inputs & outputs, not the usual gulp piped stream. So at the moment gulp-durandal can only be used at the start of a stream (like gulp.src). It ignores any input stream, and in fact runs sync regardless of any surrounding pipe. In the above example gulp-durandal runs before the newer plugin gets the stream.

I am working on a PR. Currently a bit rough, but working with gulp-newer it is avoiding building if some source files aren't changed.

**Comment by vzaidman** [comment]
True. As far as I know requireJS and streams are not combined well for now. For example in-
https://github.com/RobinThrift/gulp-requirejs :
"Because the require.js optimizer (r.js) is a kind of build system in itself we can't use the gulp.src([...]) syntax at the moment"
If anything changes, you are well come to comment here.

**Comment by danikenan** [comment]
Will not fix. 
Please use gulp-change or gulp-newer to find if a build is needed, and then call the task only if it needed.
