### ISSUE TITLE
Error : cannot read property 'normalize' of undefined

### ISSUE THREAD

**Issue by amirjelo** [welldone-software/gulp-durandal#6]
i have this gulpfile: 

var gulp = require('gulp');
var durandal = require('gulp-durandal');

gulp.task('durandal', function(){
    durandal({
            baseDir: 'App',  
            main: 'main.js',  
            output: 'main-built.js', 
            almond: true,
            minify: true
        })
        .pipe(gulp.dest('build'));
});

gulp.task('default', ['durandal']);

and when i want to build i have this error : 

![error gulp](https://cloud.githubusercontent.com/assets/3989284/3536658/5fbd93ac-0814-11e4-9eb8-98f07239b4cd.png)

pleaaasee help me ! weyland is so slow :(

**Comment by Corical** [comment]
Thanks man, helped me as well. Had to add the config dependency.

rjsConfigAdapter.deps = ['text'];
