### ISSUE TITLE
Very Slow Performance

### ISSUE THREAD

**Issue by tekmaven** [welldone-software/gulp-durandal#8]
Currently I am using gulp-durandal to minify my durandal application.  It contains a small collection of views and viewmodels.  The entire app folder contains 32 files and is 88 KB.  The durandal task takes over 2 minutes to minify this.  When using ugilfy directly on the JS (without gulp-durandal), the minification takes less than 2 seconds.

This is what my task looks like:

```
    return durandal({
            baseDir: 'App', 
            main: 'main.js', 
            output: 'app.min.js', 
            almond: true,
            minify: true,
            verbose: false
        })
        .pipe(size({title:"durandal"}))
        .pipe(gulp.dest('out'));
```
Is this a problem that other people experience?  Can you recommend any approaches to speed this up?

**Comment by petersondrew** [comment]
I'm experiencing this too, my guess is that it's something to do with uglify2 and source maps. See a similar issue upstream https://github.com/jrburke/r.js/issues/451

**Comment by danikenan** [comment]
For now, simply set minify to false. It is beyond our control. 
Hope the rjs/uglify2 guys fix it soon.
